config/routes.rb
require 'sidekiq/web'

Screamout::Engine.routes.draw do
  resources :iframe_contents
  resources :contents do
    member do
      get 'details'
    end
    collection do
      get 'tags'
    end
  end
  #root 'contents#index'
  mount Sidekiq::Web, at:'/sidekiq'
end

app/models/screamout/content.rb
module Screamout 
  class Content
    include Mongoid::Document
    include Mongoid::Timestamps
    include Mongoid::Taggable
    include Mongoid::Paperclip

    IMAGE_PATH = "#{Rails.root}/public/snapshots/"
    #IMAGE_WIDTH = 100
    IMAGE_HEIGHT = 600

    field :title, type: String
    field :url, type: String
    field :image_file_name, type:String
    has_mongoid_attached_file :photo,:styles => {:original => ['1920x1680>', :jpg],:small  => ['220x180!', :jpg]}  

    rateable range: (0..5)
    belongs_to :user
    #validates :title, presence: true
    validates :url, presence: true, uniqueness: true, format: { with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}[:]?(([0-9]{1,5})?\/?.*)$)/i}
    validates :image_file_name, presence: true
    validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "application/pdf"]


    def image_file_name=(title)
      self[:image_file_name]= title.gsub(" ","_") +"_"+ Time.now.to_i.to_s + ".jpg"
    end

    def name
      self.title
    end

    def tag_map
      tags.split(",").collect{|t| {id: t, name: t}}
    end  

    def as_json(options ={})
      options = {only: [:_id,:title, :url, :tags_array], methods: [:id, :photo_url, :name, :user_id, :user_photo_url]}
      super
    end
    
    def id
      self._id.to_s
    end
    
    def photo_url
      self.photo.url(:small)
    end

    def self.get_all_tags
      tags_hash =[]
      tags = Content.tags.sort
      tags = tags.flatten.uniq.sort
      tags.each.with_index do |tag,index|
        tags_hash << {id: tag, text: tag}
      end
      tags_hash
    end

    def name
      self.user.try(:name)
    end

    def user_id
      self.user.try(:id).try(:to_s)
    end

    def user_photo_url
      self.user.try(:public_profile).try(:image).try(:thumb).try(:url)
    end
  end
end

app/controllers/screamout/application_controller.rb
module Screamout
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    layout 'application'
    protect_from_forgery with: :exception
    before_action :check_headers

    private

    def check_headers
      response.headers.delete("X-Frame-Options")
    end

  end
end

app/controllers/screamout/contents_controller.rb
module Screamout
  class ContentsController < ApplicationController

    def index
      @contents = Content.all.desc(:created_at)   
      @con = Content.new
      @tags_hash = Content.get_all_tags
    end


    def show
      @content = Content.find(params[:id])
    end

    def new
      @content = Content.new
      @tags_hash = Content.get_all_tags
    end

    def details
      @content = Content.find(params[:id])
      @tags = @content.tags
      @tags_hash = Content.get_all_tags
      respond_to do |format|
        format.js {}
      end
    end

    def create
      @content = Content.new(content_params_input)
      @content.image_file_name = @content.title
      user ||= try(:current_user)
      @content.user = user 
      if @content.save 
        Screamout::ImageWorker.perform_async(@content.id.to_s)  
        respond_to do |format|
          format.html {redirect_to contents_path}
        end
      else
        respond_to do |format| 
          format.html { render action: 'new' }
        end
      end
    end

    def edit
      @content = Content.find(params[:id])
    end

    def destroy
      @content = Content.where(id: params[:id]).first

      if @content.destroy
        redirect_to contents_path
      else
        #flash[:notice] = ' not deleted'
        flash.now[:error] = @content.errors.messages
        render action: 'index'
      end
    end


    def update
      @content = Content.find(params[:id])
      @con = @content.tags.split(",")
      @con = tags_to_hash(@con)

      if @content.update_attributes!(update_content_params_input)
        redirect_to contents_path
      else
        render action: 'edit'
      end
    end

    def tags
      @contents = Content.tagged_with_all(/#{params[:q]}/)
      @tags = @contents.collect(&:tag_map).flatten.select{|t| t[:name] =~ /#{params[:q]}/}
      respond_to do |format|
        format.html {render html: @tags}
        format.json { render json: @tags}
      end
    end

    def content_ids
      @tags_selected = Content.tags.select{|e| e =~ /#{params[:q]}/}
      @content_selected = Content.where(:tags_array.in => @tags_selected).to_a

      respond_to do |format|
        format.html 
        format.json {render json: @content_selected}
      end
    end

    private
    def content_params_input
      params[:content][:tags]= params[:content][:tags] unless params[:content][:tags].blank?
      params.require(:content).permit(:url,:photo, :title,:rates, :tags)
    end

    def update_content_params_input
      params[:content][:tags]= params[:content][:tags].first unless params[:content][:tags].blank?
      params.require(:content).permit(:url,:photo, :title,:rates, :tags)
    end

    def tags_to_hash(cons)
      cons.map do |con|
        {id: con, name: con}
      end   
    end
  end
end

app/controllers/screamout/iframe_contents_controller.rb
module Screamout
  class IframeContentsController < ApplicationController
    layout 'screamout/iframe_application'
    before_filter :remove_xss_protection

    def new
      @content = Content.new
      @tags_hash = Content.get_all_tags
    end

    def create
      @content = Content.new(content_params_input)
      @content.image_file_name = @content.title
      user ||= try(:current_user)
      @content.user = user
      if @content.save 
        ImageWorker.perform_async(@content.id.to_s)  
        respond_to do |format|
          format.html {redirect_to contents_path}
        end
      else
        respond_to do |format| 
          format.html { render action: 'new' }        
        end
      end
    end

    private

    def content_params_input
      params.require(:content).permit(:url,:photo, :title, :tags, :rates)
    end

    def remove_xss_protection
      response.headers.delete_if { |key| key == "X-XSS-Protection" }
      response.headers['Content-Security-Policy'] = "default-src: 'self' #{request.protocol}#{request.host_with_port}"
    end
  end
end

app/helpers/screamout/application_helper.rb
module Screamout
  module ApplicationHelper
  end
end

app/views/layouts/screamout/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Screamout</title>

  <%= stylesheet_link_tag "screamout/application" %>

  <%= stylesheet_link_tag media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'screamout/application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body >

<%= yield %>

</body>
</html>

app/views/screamout/contents/_form.html.haml
.container-fluid
  = simple_form_for(@content, :html=>{:class => 'form-horizontal'}) do |f|
      
    = f.error_notification
    .row-fluid
      .div
        = f.label :url, class: "text-left"
      .div
        = f.input :url, :label => false, :placeholder => "Url", :input_html => {class: "input-xlarge margin40"}
    .row-fluid
      = f.label :title, class: "text-left"
      = f.input :title, :label =>false, :placeholder => "Title", :input_html => {class: "input-xlarge margin40"}
    .row-fuid
      = f.label :rates, class: "text-left"
      = f.input :rates, :label =>false, :input_html => {class: "input-xlarge margin40"}
    .row-fluid
      = f.label :tags, class: "text-left"
      = f.input :tags, :label =>false, :input_html => {class: 'input-xlarge tags_container margin40', multiple: true, value: "#{@tags}"}
    .row-fluid{align: 'center'}
      = f.button :submit ,'Create', :class => 'btn btn-primary'
      = link_to "Cancel","javascript:void(0)",id: 'cancel', class: 'btn btn-danger'
:javascript
  $('.tags_container').select2({tags: #{@tags_hash.to_json}, tokenSeparators: [",", " "]})
  $('#cancel').on ('click',function(){$('#myModal').modal('hide');})

app/views/screamout/contents/_form1.html.haml
- content_for :indexpg do
  = stylesheet_link_tag :blu 
.container-fluid{:style => "opacity:1;"}
  .col-md-8
    = simple_form_for(@content, :html=>{:class => 'form-horizontal', :id=>"newform"}) do |f|
      = f.error_notification
      = f.input :url, label: 'URL', :placeholder => "Url", :input_html => {class: "input-xxlarge"}
      = f.input :title, :label =>'Title', :placeholder => "Title", :input_html => {class: "input-xxlarge"}
      = f.input :rates, :label => 'Rates', :input_html => {class: "input-xxlarge"}
      = f.input :tags, :label => 'Tags', :input_html => {:id => "contentTags", class: "input-xxlarge"}
      .control-group
        = f.button :submit ,'Create', :class => 'btn btn-primary', :id => "create"
:javascript  
  $('#contentTags').select2({tokenSeparators: [",", " "], placeholder: 'Select Tag', tags: #{@tags_hash.to_json}, allowClear: true})
    

app/views/screamout/contents/create.js.haml
jQ("iframe").remove();
jQ('*','body').not("#screamout").css("opacity","1");

app/views/screamout/contents/data.html.haml
hi..
= @content.id

app/views/screamout/contents/details.js.haml
$('#myModal .modal-body').html('#{escape_javascript(render partial: 'form')}')
$('#myModal').modal('show')

app/views/screamout/contents/edit.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/screamout/contents/index.html.haml
.container
  .pull-right{align: 'center'}
    %label Drag and drop to make bookmark
    %a.btn.btn-warning{href: "javascript:void((function(d){var e=d.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','#{HOST_URL}/assets/screamout/screamout.js');e.setAttribute('id','screamoutjs');d.body.appendChild(e)})(document));", title: "Add to Bookmarks"} Screamout!!

  .row
    .span8
      = link_to t('.new', :default => t("helpers.links.new")), new_content_path, :class => 'btn btn-primary'
      = simple_form_for @con, :html => { :class => 'form-search' } do |f|
        %br
        .control-group
          = f.input :tags ,:type=> 'search', label: false, input_html: {:class => 'input-medium search-query input-xxlarge'}
           

  
  %div
    .row#content_list
     
#myModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-body

#screamout

%script#template{:type => "x-tmpl-mustache"}
  .span3.fjs-ele
    %br
    .thumbnail
      %img{src: "{{photo_url}}", class: 'custom-image-rendering'}
      {{#valid_user}}
      .bookmark-controls
        %a.btn.btn-primary.edit-control{:id => "{{id}}", href: "/screamout/contents/{{id}}/details", "data-remote" => true}
          %span.icon-edit
        %a.btn.btn-default{href:"/screamout/contents/{{id}}",data:{method:"delete" ,confirm:"Are you sure?" }}
          %span.icon.icon-trash
      {{/valid_user}}
      %a{target:"_blank" ,href:"{{url}}" }
        .bookmark-info
          .h5.truncate_text
            {{title}}
          %br
          {{#tags_array}}
          %span.label.label-default.font-10 {{.}}
          {{/tags_array}}
          .h5
            %br
            {{name}}
            %br
            {{#user_photo_url}}
            %img{src: "{{user_photo_url}}", class: 'custom-image-rendering img-polaroid'}
            {{/user_photo_url}}

/
  Bootstrap core JavaScript
/ Placed at the end of the document so the pages load faster
:javascript
  HOST_URL = "#{HOST_URL}";
  parent.window.postMessage("removetheiframe", "*");
  conc = #{@contents.to_json}  
  current_user = "#{try(:current_user).try(:id).try(:to_s)}";
  current_user_role = "#{try(:current_user).try(:role)}";
  tags_hash = #{@tags_hash.to_json}
  $(".search-query").select2({data: #{@tags_hash.to_json}, multiple: true, placeholder: 'select tags to search'})
  $(document).on('ready page:load', function(){
    loadTags();
    window.content_filter = filterInit();
  })

app/views/screamout/contents/new.html.haml
/- model_class = Content
= render :partial => 'form1'

app/views/screamout/contents/show.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
.span3.well
%table.table
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:tags_array)
        \:
    %td= @content.tags_array
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:url)
        \:
    %td= @content.url
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:image_file_name)
        \:
    %td= @content.image_file_name
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:rates)
        \:
    %td= @content.rates
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:rating)
        \:
    %td= @content.rating
  %tr
    %td
      %strong
        = model_class.human_attribute_name(:user_id)
        \:
    %td= @content.user_id
  %tr
    = image_tag(@content.photo.url(:small))
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    contents_path, :class => 'btn'                           |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_content_path(@content), :class => 'btn'             |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    content_path(@content),                                                                                      |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |

app/views/screamout/iframe_contents/_new_content2.html.haml
.iframeheading
  %h4
    %center
      %strong Screamout
.content
  .container-fluid{:style => "opacity:1;"}
    .span8
      = simple_form_for(@content, url: iframe_contents_path,
       :html=>{:class => 'form-horizontal', :id=>"newform"}) do |f|
        = hidden_field_tag :authenticity_token, form_authenticity_token
        = f.error_notification
        .row-fluid
          = f.label :url, class: 'text-left'
          = f.input :url, :label =>false, :placeholder => 'Url', input_html:{class: 'input-xxlarge margin40'}
        .row-fluid
          = f.label :title, class: 'text-left'
          = f.input :title, :label =>false, :placeholder => 'Title', input_html:{class: 'input-xxlarge margin40'}  
        .row-fluid
          = f.label :rates, class: 'text-left'
          = f.input :rates, :label =>false, input_html:{class: 'input-xxlarge margin40'}  
        .row-fluid
          = f.label :tags, class: 'text-left'
          = f.input :tags, :label =>false, :input_html => {class: 'input-xxlarge margin40', :id => "contentTags"}
        .row-fluid
          = f.button :submit ,'Create', :class => 'btn btn-primary', :id => "create"
          = f.button :button ,'Cancel', :class => 'btn btn-danger', :id => "cancel"
  :javascript
    $('#contentTags').select2({tokenSeparators: [",", " "], placeholder: 'Select Tag', tags: #{@tags_hash.to_json}})
    askData = function(){
      parent.window.postMessage("fetch", "*");
    };


    var receiveMessage = function(event){
      data = event.data.split(',');

      document.getElementById('content_title').value = data[0];
      document.getElementById('content_url').value = data[1];
    };

    $('#cancel').on ('click',function(){parent.window.postMessage("removetheiframe", "*");})
    

    window.addEventListener("message", receiveMessage, false);
    window.onload = askData;

app/views/screamout/iframe_contents/new.html.haml
= render :partial => 'new_content2'